---
title: "Aging and Longevity Data setup for RJAGS loglinear model"
output:
  html_document:
  theme: united
code_folding: show
toc: true
toc_float: true
toc_collapse: false
---
  
Purpose: Recode aging and longevity data to run loglinear model to investigate cell type specific differences
  
##Load data and libraries
```{r, setup}
#library
library(readr)
library(dplyr)
library(reshape2)
library(Seurat)

#data directory path
#PATH <- file.path("/Users/tanyatk/scc_remote/montilab-p/personal/tanya/scRNA-aging/GM_centenarians/Composition/")
PATH <- file.path("C:/Users/tkaragiannis/Documents/Data")

#datasets
reference.dat <- readRDS(file.path(PATH,"pbmc.rds"))
NECS.dat <- readRDS(file.path(PATH,"/pbmc.GMcohort.combined.rds"))

#integrate datasets in one object
pbmc.combined <- merge(reference.dat, NECS.dat, project = "PBMC.3data")

#remove objects not needed
rm(reference.dat)
rm(NECS.dat)
```

##Cell abundances table: sample v cell types
```{r, counts}
#Remove non-immune cell types
Idents(pbmc.combined) <- "ct.consensus"
pbmc.combined <- subset(pbmc.combined, idents = c("MGK", "EC", "MKI"), invert = T)

#Setup counts
counts_table <- table(pbmc.combined@meta.data$sample.ID, pbmc.combined@meta.data$ct.consensus)
```

##Recode variables for covariates
```{r, recode}
#relevel age group to set reference as CT 
#CT = 1, EL = 2
#orignal
table(pbmc.combined$age.group)
#recoding variable
pbmc.combined$age.group <- as.factor(pbmc.combined$age.group)
pbmc.combined$age.group <- relevel(pbmc.combined$age.group, "CT")
pbmc.combined$age.group <- as.integer(pbmc.combined$age.group)
pbmc.combined$age.group <- as.factor(pbmc.combined$age.group)
table(pbmc.combined$age.group)
#age group
age.group <- sapply(1:nrow(counts_table), function(x){unique(pbmc.combined@meta.data$age.group[pbmc.combined@meta.data$sample.ID %in% rownames(counts_table)[x]])})

#relevel batch variable to set reference as PNAS
#original
table(pbmc.combined$batch)
#recoding variable
pbmc.combined$batch[pbmc.combined$batch == "PNAS"] <- 1
pbmc.combined$batch[pbmc.combined$batch == "NATGEN"] <- 2
pbmc.combined$batch[pbmc.combined$batch == "COHORT.B1"] <- 3
pbmc.combined$batch[pbmc.combined$batch == "COHORT.B2"] <- 4
pbmc.combined$batch <- as.factor(pbmc.combined$batch)
table(pbmc.combined$batch)
#batch
batch <- sapply(1:nrow(counts_table), function(x){unique(pbmc.combined@meta.data$batch[pbmc.combined@meta.data$sample.ID %in% rownames(counts_table)[x]])})

#relevel sex to set reference as Male
#original
table(pbmc.combined$sex)
#recoding variable
pbmc.combined$sex <- as.factor(pbmc.combined$sex)
pbmc.combined$sex <-  relevel(pbmc.combined$sex, "Male")
pbmc.combined$sex <- as.integer(pbmc.combined$sex)
pbmc.combined$sex <- as.factor(pbmc.combined$sex)
table(pbmc.combined$sex)
#sex
sex <- sapply(1:nrow(counts_table), function(x){unique(pbmc.combined@meta.data$sex[pbmc.combined@meta.data$sample.ID %in% rownames(counts_table)[x]])})
```

##Setup mcmc object for rjags

```{r, rjags object}
rjags.data <- list(n.sample = nrow(counts_table),
             n.ct = ncol(counts_table), 
             N = apply(counts_table, 1, sum),
             X = counts_table, 
             age.group = as.factor(age.group), #age group for each cell
             batch = as.factor(batch), #batch ID for each cell
             sex = as.factor(sex) #sex for each cell
)
saveRDS(rjags.data, file.path("rjags.data.rds"))
```


